modLoader="javafml"
loaderVersion="47,)"
license="All Rights Reserved, DragN0007"
#issueTrackerURL="https://discord.gg/2WznNTtVac"
[[mods]]
modId="radrats"
version="${1.0}"
displayName="Radical Rats!"
logoFile="rad_rats_logo.png"
authors="DragN0007"
description='''
Adds Rats and decor!
'''
[[dependencies.radrats]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.radrats]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.radrats]]
modId="geckolib"
mandatory=true
versionRange = "[4.4.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.radrats]]
modId="dragnlivestock"
mandatory=true
versionRange = "[2.8,)"
ordering="NONE"
side="BOTH"